// Regenerates external/glad from the Khronos gl.xml registry.
//
// Produces a glad2-compatible loader (same public API: gladLoadGL(GLADloadfunc),
// GLAD_GL_VERSION_X_Y flags, glad_glXxx pointers behind glXxx macros) for
// OpenGL 3.3 core profile with no extensions.
//
// The gl.xml used for the committed files is the copy bundled in the PyPI
// wheel glad2-2.0.8 (sha256 cfe84018233043554710aa747d0bf4be55015154f8bcd451765d1984bcc9d70b).
// This script is NOT run by the build; it only exists so the committed output is reproducible.
//
// Usage:  node tools/gen_glad.mjs path/to/gl.xml external/glad

import fs from "node:fs";
import path from "node:path";

const [, , xmlPath, outDir] = process.argv;
if (!xmlPath || !outDir) {
  console.error("usage: node tools/gen_glad.mjs <gl.xml> <outDir>");
  process.exit(1);
}

const TARGET_API = "gl";
const TARGET_PROFILE = "core";
const TARGET_VERSION = [3, 3];

const xml = fs.readFileSync(xmlPath, "utf8");

const unescape = (s) =>
  s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, "&");
const stripTags = (s) => unescape(s.replace(/<apientry\/>/g, "APIENTRY").replace(/<[^>]+>/g, ""));
const attrs = (s) => {
  const out = {};
  for (const m of s.matchAll(/(\w+)="([^"]*)"/g)) out[m[1]] = m[2];
  return out;
};
const versionOf = (num) => num.split(".").map(Number);
const versionLE = (a, b) => a[0] < b[0] || (a[0] === b[0] && a[1] <= b[1]);

// ---- types ----------------------------------------------------------------
const typesBlock = xml.match(/<types>([\s\S]*?)<\/types>/)[1];
const typeLines = [];
for (const m of typesBlock.matchAll(/<type\b([^>]*)>([\s\S]*?)<\/type>/g)) {
  const a = attrs(m[1]);
  if (a.api && a.api !== TARGET_API) continue;
  typeLines.push(stripTags(m[2]));
}

// ---- enums ----------------------------------------------------------------
const enumValues = new Map();
for (const m of xml.matchAll(/<enum\b([^>]*?)\/?>/g)) {
  const a = attrs(m[1]);
  if (!a.name || a.value === undefined) continue;
  if (a.api && a.api !== TARGET_API) continue;
  let v = a.value;
  if (a.type === "u") v += "u";
  if (a.type === "ull") v += "ull";
  enumValues.set(a.name, v);
}

// ---- commands -------------------------------------------------------------
const commands = new Map();
const commandsBlock = xml.match(/<commands\b[^>]*>([\s\S]*?)<\/commands>/)[1];
for (const m of commandsBlock.matchAll(/<command\b[^>]*>([\s\S]*?)<\/command>/g)) {
  const body = m[1];
  const proto = body.match(/<proto\b[^>]*>([\s\S]*?)<\/proto>/)[1];
  const name = proto.match(/<name>([^<]+)<\/name>/)[1];
  const ret = stripTags(proto.replace(/<name>[^<]+<\/name>/, "")).trim();
  const params = [];
  for (const p of body.matchAll(/<param\b([^>]*)>([\s\S]*?)<\/param>/g)) {
    const pa = attrs(p[1]);
    if (pa.api && pa.api !== TARGET_API) continue;
    params.push(stripTags(p[2]).trim());
  }
  commands.set(name, { name, ret, params: params.length ? params.join(", ") : "void" });
}

// ---- features -------------------------------------------------------------
const features = [];
const wantedEnums = new Set();
const wantedCommands = new Set();
const removedEnums = new Set();
const removedCommands = new Set();
const commandVersion = new Map();

for (const m of xml.matchAll(/<feature\b([^>]*)>([\s\S]*?)<\/feature>/g)) {
  const a = attrs(m[1]);
  if (a.api !== TARGET_API) continue;
  const ver = versionOf(a.number);
  if (!versionLE(ver, TARGET_VERSION)) continue;
  features.push({ name: a.name, ver });
  for (const r of m[2].matchAll(/<(require|remove)\b([^>]*)>([\s\S]*?)<\/\1>/g)) {
    const kind = r[1];
    const ra = attrs(r[2]);
    if (ra.api && ra.api !== TARGET_API) continue;
    if (ra.profile && ra.profile !== TARGET_PROFILE) continue;
    for (const e of r[3].matchAll(/<enum\b[^>]*name="([^"]+)"/g))
      (kind === "require" ? wantedEnums : removedEnums).add(e[1]);
    for (const c of r[3].matchAll(/<command\b[^>]*name="([^"]+)"/g)) {
      if (kind === "require") {
        wantedCommands.add(c[1]);
        if (!commandVersion.has(c[1])) commandVersion.set(c[1], a.name);
      } else {
        removedCommands.add(c[1]);
      }
    }
  }
}
for (const e of removedEnums) wantedEnums.delete(e);
for (const c of removedCommands) wantedCommands.delete(c);

const enumList = [...wantedEnums].sort();
const cmdList = [...wantedCommands].sort();
for (const e of enumList) if (!enumValues.has(e)) throw new Error(`missing enum value ${e}`);
for (const c of cmdList) if (!commands.has(c)) throw new Error(`missing command ${c}`);

const pfn = (n) => `PFN${n.toUpperCase()}PROC`;

// ---- header ---------------------------------------------------------------
let h = `/**
 * OpenGL loader, glad2-compatible API.
 *
 * Generated by tools/gen_glad.mjs from the Khronos gl.xml registry.
 *   API: gl=${TARGET_VERSION.join(".")}   Profile: ${TARGET_PROFILE}   Extensions: none
 * Do not edit by hand; re-run the generator instead.
 */
#ifndef GLAD_GL_H_
#define GLAD_GL_H_

#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifdef __gl_h_
  #error OpenGL (gl.h) header already included (API: gl), remove previous include!
#endif
#define __gl_h_ 1
#ifdef __gl3_h_
  #error OpenGL (gl3.h) header already included (API: gl), remove previous include!
#endif
#define __gl3_h_ 1
#ifdef __glext_h_
  #error OpenGL (glext.h) header already included (API: gl), remove previous include!
#endif
#define __glext_h_ 1
#ifdef __gl3ext_h_
  #error OpenGL (gl3ext.h) header already included (API: gl), remove previous include!
#endif
#define __gl3ext_h_ 1
#ifdef __clang__
#pragma clang diagnostic pop
#endif

#define GLAD_GL
#define GLAD_OPTION_GL_LOADER_NONE

#ifdef __cplusplus
extern "C" {
#endif

#ifndef GLAD_PLATFORM_H_
#define GLAD_PLATFORM_H_

#if defined(_WIN32) || defined(__WIN32__) || defined(WIN32) || defined(__MINGW32__)
  #define GLAD_PLATFORM_WIN32 1
#else
  #define GLAD_PLATFORM_WIN32 0
#endif

#ifndef GLAD_PLATFORM_UWP
  #define GLAD_PLATFORM_UWP 0
#endif

#ifdef __GNUC__
  #define GLAD_GNUC_EXTENSION __extension__
#else
  #define GLAD_GNUC_EXTENSION
#endif

#define GLAD_UNUSED(x) (void)(x)

#ifndef GLAD_API_CALL
  #define GLAD_API_CALL extern
#endif

#ifndef GLAD_API_PTR
  #if GLAD_PLATFORM_WIN32 || defined(__CYGWIN__)
    #define GLAD_API_PTR __stdcall
  #else
    #define GLAD_API_PTR
  #endif
#endif

#ifndef APIENTRY
  #define APIENTRY GLAD_API_PTR
#endif
#ifndef APIENTRYP
  #define APIENTRYP APIENTRY *
#endif
#ifndef GLAPI
  #define GLAPI extern
#endif
#ifndef GLAPIENTRY
  #define GLAPIENTRY APIENTRY
#endif

#define GLAD_MAKE_VERSION(major, minor) (major * 10000 + minor)
#define GLAD_VERSION_MAJOR(version) (version / 10000)
#define GLAD_VERSION_MINOR(version) (version % 10000)

#define GLAD_GENERATOR_VERSION "gen_glad.mjs 1.0"

typedef void (*GLADapiproc)(void);
typedef GLADapiproc (*GLADloadfunc)(const char *name);
typedef GLADapiproc (*GLADuserptrloadfunc)(void *userptr, const char *name);

#endif /* GLAD_PLATFORM_H_ */

`;

for (const e of enumList) h += `#define ${e} ${enumValues.get(e)}\n`;
h += "\n";
for (const t of typeLines) h += t + "\n";
h += "\n";
for (const f of features) h += `#define ${f.name} 1\nGLAD_API_CALL int GLAD_${f.name};\n`;
h += "\n";
for (const c of cmdList) {
  const cmd = commands.get(c);
  h += `typedef ${cmd.ret} (GLAD_API_PTR *${pfn(c)})(${cmd.params});\n`;
}
h += "\n";
for (const c of cmdList) h += `GLAD_API_CALL ${pfn(c)} glad_${c};\n#define ${c} glad_${c}\n`;
h += `
GLAD_API_CALL int gladLoadGLUserPtr(GLADuserptrloadfunc load, void *userptr);
GLAD_API_CALL int gladLoadGL(GLADloadfunc load);

#ifdef __cplusplus
}
#endif
#endif /* GLAD_GL_H_ */
`;

// ---- source ---------------------------------------------------------------
let s = `/**
 * OpenGL loader, glad2-compatible API. Generated by tools/gen_glad.mjs; do not edit.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glad/gl.h>

#ifndef GLAD_IMPL_UTIL_C_
#define GLAD_IMPL_UTIL_C_
#ifdef _MSC_VER
#define GLAD_IMPL_UTIL_SSCANF sscanf_s
#else
#define GLAD_IMPL_UTIL_SSCANF sscanf
#endif
#endif /* GLAD_IMPL_UTIL_C_ */

#ifdef __cplusplus
extern "C" {
#endif

`;
for (const f of features) s += `int GLAD_${f.name} = 0;\n`;
s += "\n";
for (const c of cmdList) s += `${pfn(c)} glad_${c} = NULL;\n`;
s += "\n";
for (const f of features) {
  const mine = cmdList.filter((c) => commandVersion.get(c) === f.name);
  s += `static void glad_gl_load_${f.name}(GLADuserptrloadfunc load, void *userptr) {\n`;
  s += `    if (!GLAD_${f.name}) return;\n`;
  for (const c of mine) s += `    glad_${c} = (${pfn(c)}) load(userptr, "${c}");\n`;
  s += "}\n";
}
s += `
static int glad_gl_find_core_gl(void) {
    int i;
    const char *version;
    const char *prefixes[] = {
        "OpenGL ES-CM ",
        "OpenGL ES-CL ",
        "OpenGL ES ",
        "OpenGL SC ",
        NULL
    };
    int major = 0;
    int minor = 0;
    version = (const char *) glad_glGetString(GL_VERSION);
    if (!version) return 0;
    for (i = 0; prefixes[i]; i++) {
        const size_t length = strlen(prefixes[i]);
        if (strncmp(version, prefixes[i], length) == 0) {
            version += length;
            break;
        }
    }

    GLAD_IMPL_UTIL_SSCANF(version, "%d.%d", &major, &minor);

`;
for (const f of features)
  s += `    GLAD_${f.name} = (major == ${f.ver[0]} && minor >= ${f.ver[1]}) || major > ${f.ver[0]};\n`;
s += `
    return GLAD_MAKE_VERSION(major, minor);
}

int gladLoadGLUserPtr(GLADuserptrloadfunc load, void *userptr) {
    int version;

    glad_glGetString = (PFNGLGETSTRINGPROC) load(userptr, "glGetString");
    if (glad_glGetString == NULL) return 0;
    version = glad_gl_find_core_gl();

`;
for (const f of features) s += `    glad_gl_load_${f.name}(load, userptr);\n`;
s += `
    return version;
}

static GLADapiproc glad_gl_get_proc_from_userptr(void *userptr, const char *name) {
    return (GLAD_GNUC_EXTENSION (GLADapiproc (*)(const char *name)) userptr)(name);
}

int gladLoadGL(GLADloadfunc load) {
    return gladLoadGLUserPtr(glad_gl_get_proc_from_userptr, GLAD_GNUC_EXTENSION (void*) load);
}

#ifdef __cplusplus
}
#endif
`;

fs.mkdirSync(path.join(outDir, "include", "glad"), { recursive: true });
fs.mkdirSync(path.join(outDir, "src"), { recursive: true });
fs.writeFileSync(path.join(outDir, "include", "glad", "gl.h"), h.replace(/\r\n/g, "\n"));
fs.writeFileSync(path.join(outDir, "src", "gl.c"), s.replace(/\r\n/g, "\n"));
console.log(`features=${features.length} enums=${enumList.length} commands=${cmdList.length}`);
